### ISSUE TITLE
[BANCO DE DADOS] Desenvolvimento

### ISSUE THREAD

**Issue by devPisa** [Grupo02-SAGA/ambiente-saga#23]
### Construção de bancos de dados SQL:
> + Atualmente o banco é composto por 6 tabelas `Formulário` `Funcionário` `Perguntas` `Respostas` `Documentos` `EmpresaCliente`.
>
> [Veja o modelo Lógico](https://drive.google.com/file/d/10i4g0kEdbGJQ9sYIjrK6NEyXWEWFG_Bu/view?usp=sharing);

### Descrição dos casos de uso

> N/A

### Requisitos atendidos

> * #RNF06

### Regra de negócio

> #RGN01: banco deverá vir setado com um `ADM`;
> #RGN02: O banco deverá armazenar as perguntas que `ADM` e `FUNCIONÁRIO` fornecer na tabela `PERGUNTAS`, a tabela de perguntas poderá receber novas perguntas durante toda vida útil do software e se, somente se, a pergunta não tiver nenhuma resposta, o banco deverá permitir sua exclusão; REF:. #10 #11 #12 
> #RGN:03: O banco deverá permitir que `ADM` e `FUNCIONÁRIO` edite as perguntas de cada formulário e este formulário será armazenado na tabela `RESPOSTAS` e se, formulário não tiver nenhuma resposta, o banco deve permitir sua exclusão; REF:. #8 #9 
> #RGN04: O Banco deverá permitir que os cargos de `ADM` e `FUNCIONÁRIO` filtre seus dados;  #14

### Observações

> * O documento de regras de negócio está incompleto. Qualquer alteração deverá ser previamente comunicada.

**Comment by guiigos** [comment]
# MVP
## Banco de dados
### Usuario
- Id
- Nome
- E-mail
- Senha

### Empresa
- Id
- Fantasia
- Razão social
- CNPJ
- E-mail
- Endereço
- Telefone

### Formulario
- Titulo

### Pergunta
- Titulo

### Tabela de muitos pra muitos de Formulario e Pergunta
- FK do formulario
- FK da pergunta

### Tabela de respostas
- Resposta
- FK pergunta
- FK formulario
- FK empresa
- FK usuario

### Tabela de documentos
- URL do documento (Prioridade baixa)
- FK da resposta

**Comment by Kainak** [comment]
![ModeloLogico_saga_v3](https://github.com/Grupo02-SAGA/ambiente-saga/assets/125594835/253036b4-2ebc-48d6-a32a-c43ae0bc887b)

**Comment by guiigos** [comment]
Verificar relacionamento entre usuário e funcionário, conceitualmente me parece a mesma coisa!

**Comment by guiigos** [comment]
Verificar se realmente faz sentido o relacionamento de muitos (funcionario) para um (empresa) do funcionário com a empresa.

**Comment by Kainak** [comment]
![Image](https://github.com/Grupo02-Biopark/ambiente-saga/assets/125594835/9278fdcb-de5d-4130-8b7e-c37bc2db9f7e)



> MUDANÇAS

- Atributo base no formulário - Identifica se é um formulário base ou não;

- Foreign keys na tabela respostas: Agora são referentes às tabelas formulário e perguntas separadamente

- Atributo validado no documento: Vai ser usado no final para conferir se todos os documentos estão certos e só então gerar a nota do certificado e mostrar na tela
